version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: yarn
          command: yarn
      - run:
          name: test
          command: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
